// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title Atomic-Verify Settlement Protocol (Phase 1)
 * @author Your Name
 * @notice This contract implements a "Time-Locked Escrow" for the Atomic-Verify project.
 * It solves the "Reconciliation Lag" problem by holding funds until a service is cryptographically verified.
 */
contract AtomicEscrow {
    
    // --- STATE VARIABLES ---

    address public owner; // The address of the deployer (You/The Oracle Backend)
    
    // Enum to track the lifecycle of a payment
    enum PaymentStatus { PENDING, COMPLETED, REFUNDED }

    // Struct to hold all details of a single transaction
    struct Transaction {
        address payable user;    // Who sent the money
        address payable merchant;// Who gets the money (e.g., YouTube's wallet)
        uint256 amount;          // How much (in Wei)
        uint256 timestamp;       // When the payment started
        PaymentStatus status;    // Current status (Pending/Completed/Refunded)
        bool isLocked;           // Security flag to prevent re-entrancy
    }

    // A mapping to store all transactions by a unique ID
    mapping(bytes32 => Transaction) public transactions;

    // --- EVENTS (This is how your Node.js Backend "hears" the blockchain) ---
    
    // Emitted when a user clicks "Pay Now"
    event PaymentInitiated(bytes32 indexed transactionId, address indexed user, uint256 amount);
    
    // Emitted when the payment succeeds
    event FundsReleased(bytes32 indexed transactionId, address merchant, uint256 amount);
    
    // Emitted when the refund happens
    event RefundExecuted(bytes32 indexed transactionId, address user, uint256 amount, string reason);

    // --- MODIFIERS ---
    
    // Only the Oracle (your backend) can call specific functions
    modifier onlyOwner() {
        require(msg.sender == owner, "Only the Oracle/Backend can trigger this");
        _;
    }

    constructor() {
        owner = msg.sender; // Set the deployer as the owner
    }

    // --- CORE FUNCTIONS ---

    /**
     * @dev Step 1: The User calls this function to start the payment.
     * @param _merchant The wallet address of the service provider (YouTube).
     * @param _transactionId A unique ID generated by your frontend (UUID).
     */
    function depositFunds(address payable _merchant, bytes32 _transactionId) external payable {
        require(msg.value > 0, "You must send ETH to create an escrow");
        require(transactions[_transactionId].amount == 0, "Transaction ID already exists");

        // Create the transaction record in the blockchain "ledger"
        transactions[_transactionId] = Transaction({
            user: payable(msg.sender),
            merchant: _merchant,
            amount: msg.value,
            timestamp: block.timestamp, // Record the exact time (in seconds)
            status: PaymentStatus.PENDING,
            isLocked: true
        });

        // Emit event so the Backend/Oracle knows to start checking the API
        emit PaymentInitiated(_transactionId, msg.sender, msg.value);
    }

    /**
     * @dev Step 2a (Happy Path): Called by your Backend Oracle if API returns 200 OK.
     * @param _transactionId The ID of the transaction to finalize.
     */
    function finalizeTransaction(bytes32 _transactionId) external onlyOwner {
        Transaction storage txn = transactions[_transactionId];

        require(txn.isLocked, "Transaction is not active");
        require(txn.status == PaymentStatus.PENDING, "Transaction already finalized");

        // Update state *before* transfer to prevent re-entrancy attacks
        txn.status = PaymentStatus.COMPLETED;
        txn.isLocked = false;

        // Transfer funds to the Merchant
        (bool success, ) = txn.merchant.call{value: txn.amount}("");
        require(success, "Transfer to merchant failed");

        emit FundsReleased(_transactionId, txn.merchant, txn.amount);
    }

    /**
     * @dev Step 2b (Refund Path): Called if API fails OR Time expires (60s).
     * @param _transactionId The ID of the transaction to refund.
     */
    function refundUser(bytes32 _transactionId) external {
        Transaction storage txn = transactions[_transactionId];

        require(txn.isLocked, "Transaction is not active");
        require(txn.status == PaymentStatus.PENDING, "Transaction already processed");

        // --- THE ATOMIC TIMEOUT LOGIC ---
        // We allow the refund if:
        // 1. The Owner (Backend) calls it explicitly (Simulate Failure button)
        // OR
        // 2. The original user calls it (for failed verifications)
        // OR
        // 3. 60 seconds have passed and the transaction is still stuck (Automatic safety)
        bool isOwner = msg.sender == owner;
        bool isUser = msg.sender == txn.user;
        bool isExpired = block.timestamp > txn.timestamp + 60; // 60 seconds timeout

        require(isOwner || isUser || isExpired, "Only user, owner, or after timeout can refund");

        // Update state
        txn.status = PaymentStatus.REFUNDED;
        txn.isLocked = false;

        // Return funds to the User
        (bool success, ) = txn.user.call{value: txn.amount}("");
        require(success, "Refund transfer failed");

        emit RefundExecuted(_transactionId, txn.user, txn.amount, isExpired ? "Timeout Expired" : (isOwner ? "Oracle Triggered" : "User Requested"));
    }
}